// Creates a portable, read-only gallery of locally verified screenshots.
import fs from 'node:fs';
import path from 'node:path';
const dir = path.resolve('artifacts/ui');
const screens = [
  ['home-populated', 'ホーム'], ['timer', 'タイマー'], ['memorize', '暗記ライブラリ'], ['timeline', 'タイムライン'],
  ['conversations', 'メッセージ'], ['friends', 'フレンド'], ['subjects', '教科'], ['preferences', 'アプリ設定'], ['settings', 'アカウント設定'], ['ranking', 'ランキング'],
  ['memorize-deck-test-deck', '単語帳詳細'], ['memorize-deck-test-deck-edit', 'カード編集'], ['memorize-create-deck', '単語帳作成'], ['memorize-create-question', '問題作成'], ['memorize-questions', '問題一覧'],
  ['memorize-review-test-deck', '暗記カード'], ['memorize-review-test-deck-done', '暗記完了'], ['memorize-test-deck-test-deck', 'テスト設定'], ['memorize-test-deck-test-deck-run', '単語テスト'], ['memorize-test-test-question', '穴埋めテスト'],
  ['support', 'お問い合わせ'], ['announcements', 'お知らせ'], ['missions', 'ミッション'], ['onboarding', '初回設定'], ['login', 'ログイン'],
].map(([id, label]) => ({ id, label, images: Object.fromEntries([390, 820, 1440].filter(width => fs.existsSync(path.join(dir, `${id}-${width}.png`))).map(width => [width, 'data:image/png;base64,' + fs.readFileSync(path.join(dir, `${id}-${width}.png`)).toString('base64')])) }));
const html = `<!doctype html><html lang="ja"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>StudyFlow 改修画面プレビュー</title><style>
*{box-sizing:border-box}body{margin:0;background:#f1f2f5;color:#202124;font:15px/1.6 system-ui,sans-serif}header{padding:24px 28px;background:#fff;border-bottom:1px solid #ddd}h1{font-size:24px;letter-spacing:-.04em;margin:0}p{margin:6px 0;color:#64748b}nav{display:flex;flex-wrap:wrap;gap:10px;padding:16px 28px;background:#fff;position:sticky;top:0;z-index:2;border-bottom:1px solid #ddd}select,button{min-height:44px;border:1px solid #ddd;border-radius:8px;background:#fff;padding:8px 14px;font:inherit;color:inherit}button[aria-pressed=true]{background:#5145ed;color:white;border-color:#5145ed}.preview{padding:24px;overflow:auto;text-align:center}.preview img{display:block;margin:auto;max-width:100%;height:auto;border:1px solid #ddd;border-radius:8px;box-shadow:0 12px 40px #0000000d}footer{padding:16px 28px;color:#64748b;font-size:13px}@media(max-width:600px){header,nav,footer{padding:16px}.preview{padding:12px}select{width:100%}}
</style><header><h1>StudyFlow 改修画面プレビュー</h1><p>左上の装飾アイコンを廃止し、各ページの内部配置を再設計しました。</p><p>ローカルのテストデータを使った実装画面です。本番データ・実機検証とは区別しています。</p></header><nav aria-label="プレビューを選択"><select aria-label="画面"></select><div><button data-width="390">スマホ</button> <button data-width="820">iPad</button> <button data-width="1440">PC</button></div></nav><main class="preview"><img alt="改修画面"></main><footer>390 / 820 / 1440 px。長い画面は下にスクロールして確認できます。フォーム操作は静止画です。</footer><script>
const screens=${JSON.stringify(screens)};let width=1440;const select=document.querySelector('select'),img=document.querySelector('img');screens.forEach((s,i)=>{const o=document.createElement('option');o.value=i;o.textContent=s.label;select.append(o)});function show(){const s=screens[select.value||0];img.src=s.images[width];img.style.width=width+'px';img.alt=s.label+' '+width+'px';document.querySelectorAll('button').forEach(b=>b.setAttribute('aria-pressed',Number(b.dataset.width)===width?'true':'false'))}select.addEventListener('change',show);document.querySelectorAll('button').forEach(b=>b.addEventListener('click',()=>{width=Number(b.dataset.width);show()}));show();</script></html>`;
const target = path.join(dir, 'index.html'); fs.writeFileSync(target, html); console.log(target);
